### ISSUE TITLE
Incorrect parsing for e-mail with subject and body 

### ISSUE THREAD

**Issue by sridhareaswaran** [pocka/slack-message-parser#13]
Simple email format parsing is working fine, however parsing for e-mail with subject and body isn't working.

#### Working Example
<mailto:sri@example.com|email friend 👍 >
##### output:
Object { label: [Object {text: "email friend 👍", type: 0}], type: 3, url: "mailto:sri@example.com"}

#### Not working Example
<mailto:?subject=Job Opening - Backend Engineer - New York&body=Hi,%0D%0A %0D%0A I found a job opening for Backend Engineer at New York and thought you might be interested. %0D%0A %0D%0ACheck out the link for more details. %0D%0Ahttps://www.example.com/f/d/task/1234.htmld|Share with colleagues> 
##### output:
parse into three different parts as follows: 

1. " <mailto"
2. ?subject=Job Opening - Backend Engineer - New York&body=…A %0D%0ACheck out the link for more details. %0D%0Ahttps"
3. "//www.example.com/f/d/task/1234.htmld|Share with colleagues>"

**Comment by pocka** [comment]
This happens when you includes spaces in mailto section (in the example, both subject and body).

According to [mailto URL scheme](https://www.ietf.org/rfc/rfc2368.txt), spaces must be encoded to `%20`. But it seems that Slack accepts mailto link includes spaces so we should accept too...

**Comment by pocka** [comment]
fixed in [v1.0.5](https://github.com/pocka/slack-message-parser/blob/master/CHANGELOG.md#105---2019-08-29)
