### ISSUE TITLE
FR: Add conversion from newline to <br/> tag

### ISSUE THREAD

**Issue by sridhareaswaran** [pocka/slack-message-parser#19]
Feature Request:

Add functionality to convert newline ("\n") to html <br/> tag.

**Comment by pocka** [comment]
@sridhareaswaran 
This library is for parsing Slack messages, not for formatting to display. So text manipulation is out of the scope of this project.

Though it depends on your way of generating an html string from parse results, you can replace `\n` to `<br/>` easily.

```ts
const toHTML = (node: Node): string => {
  switch (node.type) {
    // ...
    case NodeType.Text:
      return node.text.replace('\n', '<br/>')
    // ...
  }
}
```

... or use [`white-space` CSS property](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space).

```css
selector-for-slack-text {
  white-space: pre-wrap;
}
```
