### ISSUE TITLE
In-word formatting does not appear to parse

### ISSUE THREAD

**Issue by garyposter** [pocka/slack-message-parser#26]
Hi. I like this library's API, thank you!

`*s_t_*a*_r_t*` doesn't seem to parse correctly. It stays as text. As far as I can tell any in-word formatting doesn't parse, e.g. `*s_tar_t*`sees the bold but not the italic.

Not a showstopper for me, but it would be lovely to have it addressed.

**Comment by garyposter** [comment]
I looked in the code and tests and see that the current behavior is intended in the library. I can verify that Slack now parses and generates the code I gave for in-word formatting. Perhaps it changed when they introduced the WYSIWYG interface?

Please let me know if you'd be open to a PR from me that implements the current Slack behavior.

**Comment by pocka** [comment]
> Perhaps it changed when they introduced the WYSIWYG interface?

Yes, before the new WYSIWYG editor, users couldn't decorate texts (such as `*`,  `_`, and backquote) without spaces or [punctuations](https://github.com/pocka/slack-message-parser/issues/7).

PRs are welcome! I'll check the new Slack's behavior and make a patch by myself if there are no PRs (but no release date guarantees :persevere:).

**Comment by pocka** [comment]
It's not documented though (yet?), Slack API now returns message histories with `blocks` property attached. That "block" is the same as what we send to the API.
If you want to parse the new format that was introduced by the WYSIWYG editor, please retrieve the property (until we implement in-word format parsing or Slack documents that property).

**Comment by pocka** [comment]
It seems it's impossible to parse the new format texts correctly...

---

I sent messages below (`ab*cd*ef` and <code>ab**cd**ef</code>)

![app slack com_client_T02DB2PUW_D01B2MV5VDX](https://user-images.githubusercontent.com/13316015/93208905-47358180-f798-11ea-9f09-61a27c96e29a.png)

then call `conversations.history` API. Here is the result:

```json
{
    "ok": true,
    "messages": [
        {
            "type": "message",
            "text": "`ab*cd*ef`",
            "ts": "1600171749.002700",
            "blocks": [
                {
                    "type": "rich_text",
                    "block_id": "7r2t",
                    "elements": [
                        {
                            "type": "rich_text_section",
                            "elements": [
                                {
                                    "type": "text",
                                    "text": "ab",
                                    "style": {
                                        "code": true
                                    }
                                },
                                {
                                    "type": "text",
                                    "text": "cd",
                                    "style": {
                                        "bold": true,
                                        "code": true
                                    }
                                },
                                {
                                    "type": "text",
                                    "text": "ef",
                                    "style": {
                                        "code": true
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        },
        {
            "type": "message",
            "text": "`ab*cd*ef`",
            "ts": "1600171729.002400",
            "blocks": [
                {
                    "type": "rich_text",
                    "block_id": "kjv",
                    "elements": [
                        {
                            "type": "rich_text_section",
                            "elements": [
                                {
                                    "type": "text",
                                    "text": "ab*cd*ef",
                                    "style": {
                                        "code": true
                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ],
    "has_more": false,
    "pin_count": 0,
    "channel_actions_ts": null,
    "channel_actions_count": 0
}
```

(unnecessary fields such as user id or team id are omitted)

As you can see, different messages may result in the same text.

---

For now, I'm waiting for Slack documents the new `blocks` property in `conversations.history`.

**Comment by 2naive** [comment]
I still see the same behavior.
Don't you have any ideas? May be shall we write to Slack support?

**Comment by pocka** [comment]
I sent a message to Slack support and they said that 1) there is no plan to make the `text` field be parsable 2) they will (may?) update the `conversation.history` docs. I think 1 is very reasonable and parsing the Blocks would be more reliable.

Therefore, this library will not (cannot) support correctly parsing the `text` property on messages composed by the WSYIWYG editor.

I'd recommend you to handle `blocks` then fallback to `text` parsing if there is no `blocks` property or your app failed to parse the `blocks`.

**Comment by KonstantinKudelko** [comment]
> I sent a message to Slack support and they said that 1) there is no plan to make the `text` field be parsable 2) they will (may?) update the `conversation.history` docs. I think 1 is very reasonable and parsing the Blocks would be more reliable.
> 
> Therefore, this library will not (cannot) support correctly parsing the `text` property on messages composed by the WSYIWYG editor.
> 
> I'd recommend you to handle `blocks` then fallback to `text` parsing if there is no `blocks` property or your app failed to parse the `blocks`.

@pocka do you know any lib which could parse `blocks` data from the slack API?

**Comment by pocka** [comment]
@KonstantinKudelko You don't need any library to parse the Blocks ([reference](https://api.slack.com/reference/block-kit/blocks)). If you need a type definition for that, you can use https://github.com/slackapi/bolt-js.
