### ISSUE TITLE
Node source text

### ISSUE THREAD

**Issue by 2naive** [pocka/slack-message-parser#29]
Hi,

Would be nice if we may have the source text of the node element to let us use
```
const toHTML = (node: Node): string => {
  switch (node.type) {
    ...
    default:
      return node.source
  }
}
```

Different node types have their own structure. In case of unhandled node type we may want to leave that block "as is", not removing it with `return ""` as in example

Thanks!

**Comment by pocka** [comment]
Available in [v1.1.0](https://github.com/pocka/slack-message-parser/releases/tag/v1.1.0).
