### ISSUE TITLE
Code element children

### ISSUE THREAD

**Issue by 2naive** [pocka/slack-message-parser#32]
Hi,

As written here: https://github.com/pocka/slack-message-parser/blob/master/src/types/Node.ts#L82
Code type has just text param not children.

But "into the wild" we have messages like:
text: '*<https://github.com/compare/bfa9db24b42a...e304a71a7829|1 new commit> pushed  to `<https://github.com/tree/development|development>` by User*\n`<https://github.com/commit/e304a71a7819683672dab56185f9|e304a72a>` - add field in the service'

-- generated by Apps or:

text: '<code><http://test.io></code>',

-- written by Slack message interface itself.

So nested elemets for code are valid.

In that case shouldn't we add 'children'?

Thanks!

**Comment by 2naive** [comment]
To reproduce in Slack:

1. Write github.com
2. Prepend it with `
3. Append it with `

At point 1. Slack will make it a link automatically.
At point 3. Slack will make quote block, but link remains.

**Comment by pocka** [comment]
Same as #26, there is no way to distinguish between the message written in traditional markdown-like syntax and the one composed by the WYSIWYG editor. If you want to parse messages composed by the WYSIWYG editor, parse the `blocks` property (not yet documented though) that is an AST-like tree of [Block Kit](https://api.slack.com/block-kit).
