### ISSUE TITLE
Support multiline quote without ">>>"

### ISSUE THREAD

**Issue by petejodo** [pocka/slack-message-parser#38]
Multi-line quotes aren't working as expected. The following string

```
This is unquoted text\n&gt; This is quoted text\n&gt; This is still quoted text\nThis is unquoted text again
```
renders like [the following in slack](https://app.slack.com/block-kit-builder/T0181DYT9KN#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22This%20is%20unquoted%20text%5Cn%3EThis%20is%20quoted%20text%5Cn%3EThis%20is%20still%20quoted%20text%5CnThis%20is%20unquoted%20text%20again%22%7D%7D%5D%7D):

<img width="328" alt="Screenshot 2023-06-01 at 6 00 21 PM" src="https://github.com/pocka/slack-message-parser/assets/1938892/da9643c3-8fc2-4643-aca3-36143a626d9a">

but the tree outputted looks like:

```json
{
    "type": 12,
    "children": [
        {
            "type": 0,
            "text": "This is unquoted text\n",
            "source": "This is unquoted text\n"
        },
        {
            "type": 11,
            "children": [
                {
                    "type": 0,
                    "text": " This is quoted text",
                    "source": " This is quoted text"
                }
            ],
            "source": "&gt; This is quoted text\n"
        },
        {
            "type": 11,
            "children": [
                {
                    "type": 0,
                    "text": " This is still quoted text",
                    "source": " This is still quoted text"
                }
            ],
            "source": "&gt; This is still quoted text\n"
        },
        {
            "type": 0,
            "text": "This is unquoted text again",
            "source": "This is unquoted text again"
        }
    ],
    "source": "This is unquoted text\n&gt; This is quoted text\n&gt; This is still quoted text\nThis is unquoted text again"
}
```

**Comment by petejodo** [comment]
I'm not exactly sure how multi-line quotes are supposed to work but I suspect it may have to do with this line https://github.com/pocka/slack-message-parser/blob/master/parser.ts#L96

**Comment by pocka** [comment]
Currently block quote is output by line-by-line.
The multiline quote parser is for the undocumented[^0] multiline quote marker `>>>` ([demo](https://app.slack.com/block-kit-builder/T02DB2PUW#%7B%22blocks%22:%5B%7B%22type%22:%22section%22,%22text%22:%7B%22type%22:%22mrkdwn%22,%22text%22:%22This%20is%20unquoted%20text%5Cn%3E%3E%3EThis%20is%20quoted%20text%5CnThis%20is%20still%20quoted%20text%5CnThis%20is%20unquoted%20text%20again%22%7D%7D%5D%7D)).

I believe supporting this style is not that hard with or without a new parser combinator.

[^0]: https://web.archive.org/web/20191230214525/https://api.slack.com/reference/surfaces/formatting#block-formatting

> but I suspect it may have to do with this line https://github.com/pocka/slack-message-parser/blob/master/parser.ts#L96

Honestely I'm not sure exactly what this is doing, perhaps for [this](https://github.com/pocka/slack-message-parser/blob/8ae7d6d8091fb74ec2d21b595657e575be0707d5/mod_test.ts#L220-L222)?

**Comment by pocka** [comment]
[v3.0.2](https://github.com/pocka/slack-message-parser/releases/tag/v3.0.2)
