### ISSUE TITLE
Proposal: bullet-list node type

### ISSUE THREAD

**Issue by petejodo** [pocka/slack-message-parser#39]
bullet lists are kind of annoying to deal with that can be made much easier if the parser returned back a node representing a bulleted list. For example, `"Here is a bullet list:\n• first bullet, top-level\n• second bullet, also top-level\n    ◦ nested bullet under the second bullet\n    ◦ another nested bullet\n• un-nested final bullet"` gets parsed as just a single text node.

```json
{
    "type": 12,
    "children": [
        {
            "type": 0,
            "text": "Here is a bullet list:\n• first bullet, top-level\n• second bullet, also top-level\n    ◦ nested bullet under the second bullet\n    ◦ another nested bullet\n• un-nested final bullet",
            "source": "Here is a bullet list:\n• first bullet, top-level\n• second bullet, also top-level\n    ◦ nested bullet under the second bullet\n    ◦ another nested bullet\n• un-nested final bullet"
        }
    ],
    "source": "Here is a bullet list:\n• first bullet, top-level\n• second bullet, also top-level\n    ◦ nested bullet under the second bullet\n    ◦ another nested bullet\n• un-nested final bullet"
}
```

Here's how that gets rendered in slack:

![Screenshot 2023-06-05 at 12 21 14 PM](https://github.com/pocka/slack-message-parser/assets/1938892/86dc72dd-fddb-43a0-b6dd-f952987570e5)

This becomes more difficult to manage once other nodes come into the mix.

Here's a sketch of what a supposed bullet node could look like:

```json
{
    "type": 12,
    "children": [
        {
            "type": 0,
            "text": "Here is a bullet list:\n",
            "source": "Here is a bullet list:\n"
        },
        {
            "type": 13,
            "source": "• first bullet, top-level\n• second bullet, also top-level\n    ◦ nested bullet under the second bullet\n    ◦ another nested bullet\n• un-nested final bullet",
            "children": [
                {
                    "type": 0,
                    "text": "first bullet, top-level\n",
                    "source": "• first bullet, top-level\n"
                },
                {
                    "type": 0,
                    "text": "second bullet, also top-level\n",
                    "source": "• second bullet, also top-level\n"
                },
                {
                    "type": 13,
                    "source": "    ◦ nested bullet under the second bullet\n    ◦ another nested bullet\n",
                    "children": [
                        {
                            "type": 0,
                            "text": "nested bullet under the second bullet\n",
                            "source": "• nested bullet under the second bullet\n"
                        },
                        {
                            "type": 0,
                            "text": "another nested bullet\n",
                            "source": "• another nested bullet\n"
                        }
                    ]
                },
                {
                    "type": 0,
                    "text": "un-nested final bullet",
                    "source": "• un-nested final bullet"
                },
            ]
        }
    ],
    "source": "Here is a bullet list:\n• first bullet, top-level\n• second bullet, also top-level\n    ◦ nested bullet under the second bullet\n    ◦ another nested bullet\n• un-nested final bullet"
}
```

Originally I had a `level` field to represent how nested it was but I don't think that's actually necessary. This isn't correct though because it can't handle a group of nodes for a single bullet item (e.g. text and a url in one bullet). Leaving it here though as an idea

**Edit:** another thing I missed is numbered bullets but that shouldn't be difficult, just a property on the bullet list node

**Edit 2:** I take that back, numbered lists are tricky because it's open for interpretation e.g. do the numbers have to be consecutive per line like `1. line one\n 2. line two\n` or can it be any number like `1. line one\n 1. line two\n`

**Comment by pocka** [comment]
There is no list syntax in the Slack message format. You should use `blocks` property for the WYSIWYG elements, although the advanced rich text things seems to be completely lacking reference document (only I could find is [a StackOverflow answer](https://stackoverflow.com/a/68483110/11742066) and [Slack Changelog post from 2019](https://api.slack.com/changelog/2019-09-what-they-see-is-what-you-get-and-more-and-less)).

https://api.slack.com/reference/surfaces/formatting#block-formatting__lists
