### ISSUE TITLE
Incomplete punctuation mark matching

### ISSUE THREAD

**Issue by luka-n** [pocka/slack-message-parser#7]
For bold/italic/strike, currently only period and comma match as punctuation. I'm not sure how to cover all possible punctuation here.

I was looking at this:

http://xregexp.com/plugins/

It has a matcher for all punctuation characters in unicode.

**Comment by pocka** [comment]
> For bold/italic/strike, currently only period and comma match as punctuation. 

Could you give me a list of characters you know treated as punctuations in Slack?

>  I'm not sure how to cover all possible punctuation here.

We don't need to cover all punctuations at now, IMO.
Since there is no detailed document about Slack's message syntax, my stance on message parsing  is "fix when someone pointed out "

**Comment by luka-n** [comment]
That's a reasonable approach. For now I'd reckon at least add question and exclamation marks.

**Comment by pocka** [comment]
fixed in [v1.0.5](https://github.com/pocka/slack-message-parser/blob/master/CHANGELOG.md#105---2019-08-29)
